---
name: Build and Deploy Frontend to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: npm install

    # - name: Test
    #   run: npm run test

    - name: Pre-Deploy
      run: cd client

    - name: Deploy
      run: npm run deploy